"""Members table

Revision ID: f8f9a249f2aa
Revises: 93346c5a4f52
Create Date: 2019-12-31 18:02:46.144119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f9a249f2aa'
down_revision = '93346c5a4f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('address_street', sa.String(length=64), nullable=True),
    sa.Column('address_city', sa.String(length=32), nullable=True),
    sa.Column('address_postcode', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('mobile', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_email'), 'member', ['email'], unique=False)
    op.create_index(op.f('ix_member_mobile'), 'member', ['mobile'], unique=False)
    op.create_index(op.f('ix_member_name'), 'member', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_name'), table_name='member')
    op.drop_index(op.f('ix_member_mobile'), table_name='member')
    op.drop_index(op.f('ix_member_email'), table_name='member')
    op.drop_table('member')
    # ### end Alembic commands ###
